name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: build ipfs-cluster
        run: |
          docker-compose build

      - name: docker login
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login harbor.lindensys.com --username=${username} --password=${password}

      - name: push ipfs-cluster
        run: |
          docker-compose push








